### ISSUE TITLE
Constant Apple ID request on the simulator

### ISSUE THREAD

**Issue by alexflm** [adaptyteam/AdaptySDK-iOS#66] opened 2023-09-13 12:43 UTC
Hello!

I get an Apple ID authorization request every time I run the app on the simulator. Is this how it should be? If so, it would be nice if you could add the ability to disable this for debug mode. I didn't have such a problem with the RC service.

**Adapty Mode**

observer

**Adapty SDK Version**

2.7.0

**Xcode Version**

14.3.1

**Installation Method**

SPM

**Targeted Platforms**

iOS

**Comment by snowtema** [comment] 2023-09-16 14:26
The same problem

**Comment by x401om** [comment] 2023-10-11 11:20
Hi, guys. Thank you for reaching out. This behavior is caused by our internal logic, which requests receipt from StoreKit. The only way we can eliminate this behavior is by adding support for StoreKit configuration files. For now, we have plans to add this option in Q1, 2024.

**Comment by ondrejkorol** [comment] 2023-11-25 08:47
Hi @x401om ,
I'm seeing this issue on real devices as well (when building from Xcode using debug/release configuration).
Just calling Adapty.activate(...) will trigger this alert right after the launch. Does it mean even our testers via TestFlight will experience this? Is there anything we can do to postpone the alert until it's needed (checking the subscription, restoring purchases etc)?
Thanks!

**Comment by x401om** [comment] 2024-03-07 20:00
Hi everyone! In version 2.10.0 of our SDK, we've updated how we handle StoreKit receipts. Starting from iOS 15.0, receipts are no longer needed for all devices, eliminating Apple ID Authorization requests. 

However, please keep in mind that the receipt is still essential for Adapty SDK to work correctly. You might see this pop-up on simulators before iOS 15 and occasionally in production if the user isn't authorized at the moment and the device runs a version prior to iOS 15. 

Considering the original request is fulfilled, I'm closing the issue.

**Closed by x401om** 2024-03-07 20:00 UTC
Labels: enhancement
