### ISSUE TITLE
Adapty SDK is failing to send an ever-growing event log to Kinesis

### ISSUE THREAD

**Issue by sesm** [adaptyteam/AdaptySDK-iOS#63] opened 2023-03-14 16:59 UTC
### Scenario:

- For some reason Adapty SDK accumulated a large event log
- Attempting to post events to Kinesis fails because event log size is too big: `Member must have length less than or equal to 500`
- Event log is still growing, posted to Kinesis and rejected every minute

### Screenshot:

<img width="754" alt="Screenshot 2023-03-13 at 23 56 29" src="https://user-images.githubusercontent.com/1313744/225077246-fb7e8653-897a-4e57-9312-3b0f6561cf80.png">

### Environment:
Reproduced with both `1.16.8` and `1.17.1` version of iOS SDK. Used through `react-native-adapty`, but event log logic is untouched by JS code, so posting this issue here.

### Questions:
Is this edge case fixed in 2.x version? Can this fix be backported to 1.x branch?

**Comment by sesm** [comment] 2023-03-14 18:56
Figured out why events start piling up: when app is left open for a long time requests to Kinesis start failing with `{"__type":"ExpiredTokenException","message":"The security token included in the request is expired"}` This error goes away after app restart, so I assume the token is updated on SDK initialisation. But I guess this token should be periodically updated when app is open too.

If more than 500 events pile up while the app is open, it can no longer recover after restart (because of `Member must have length less than or equal to 500` error from Kinesis) , and we get the issue described above.

<img width="1156" alt="Screenshot 2023-03-14 at 19 45 55" src="https://user-images.githubusercontent.com/1313744/225107996-eb996635-ea58-46a2-8f00-b4db9350be41.png">

**Comment by x401om** [comment] 2023-03-14 22:06
Hey, @sesm! Thank you for your detailed description of the issue! First of all, indeed, in versions before 2.x.x our SDK had a bug that caused the credentials for kinesis to update incorrectly, so that the events started to pile up. We fixed this, so in the new versions you will not face the situation of accumulation of events up to 500. However, this case can still occur during migration. We plan to fix this in upcoming releases on iOS, and make sure the problem is not present on Android. As soon as the problem is fixed, I will let you know. The fix will also hit the React native SDK as quickly as possible!

**Comment by sesm** [comment] 2023-03-14 22:17
@x401om thanks for the quick response!

**Comment by x401om** [comment] 2023-04-10 08:30
Hey, @sesm! We have completely redesigned the event reporting system in the [2.4.3](https://github.com/adaptyteam/AdaptySDK-iOS/releases/tag/2.4.3), dropping Kinesis. In the next few days the update will be available for other platforms, including React Native. Unfortunately, we don't plan to do the same for older versions of the SDK, as the code base is pretty much split up.
For the moment, I will close the issue. Please reopen it if you have any questions.

**Closed by x401om** 2023-04-10 08:30 UTC
Labels: bug

**Comment by sesm** [comment] 2023-04-19 17:49
@x401om this is fine for me, thanks for the update!
